_target_: src.datamodules.flame_mesh.FlameMeshDataModule

batch_size: 2
num_workers: 4
pin_memory: true

dataset_config: ${dataset}
data_src: ${dataset.data_src}
train_source_voca: ["vocaset_train.csv"]
valid_source_voca: []
train_source_coma: ["coma_train.csv"]
valid_source_coma: []
valid_source_talk: []
