_target_: src.datamodules.talk_and_flame.TalkAndFlameDataModule

batch_size: 2
num_workers: 4
pin_memory: true

dataset_config: ${dataset}

train_source_talk_video: ["train.csv"]
valid_source_talk_video: ["valid.csv"]
train_source_flame_mesh: ["vocaset_train.csv"]
valid_source_flame_mesh: []
