do: ['misc']

default_extra:
  swap: [
    "${path.dataset_dir}/talk_video/celebtalk/data/${model.visualizer.speaker}/fitted/trn-000/meshes",
    "${path.dataset_dir}/talk_video/celebtalk/data/${model.visualizer.speaker}/fitted/trn-001/meshes",
    "${path.dataset_dir}/talk_video/celebtalk/data/${model.visualizer.speaker}/fitted/trn-002/meshes",
    "${path.dataset_dir}/talk_video/celebtalk/data/${model.visualizer.speaker}/fitted/trn-003/meshes",
    "${path.dataset_dir}/talk_video/celebtalk/data/${model.visualizer.speaker}/fitted/trn-004/meshes",
    "${path.dataset_dir}/talk_video/celebtalk/data/${model.visualizer.speaker}/fitted/trn-005/meshes",
    "${path.dataset_dir}/talk_video/celebtalk/data/${model.visualizer.speaker}/fitted/trn-006/meshes",
    "${path.dataset_dir}/talk_video/celebtalk/data/${model.visualizer.speaker}/fitted/trn-007/meshes",
    "${path.dataset_dir}/talk_video/celebtalk/data/${model.visualizer.speaker}/fitted/trn-008/meshes",
    "${path.dataset_dir}/talk_video/celebtalk/data/${model.visualizer.speaker}/fitted/trn-009/meshes",
    "${path.dataset_dir}/talk_video/celebtalk/data/${model.visualizer.speaker}/fitted/trn-010/meshes",
    "${path.dataset_dir}/talk_video/celebtalk/data/${model.visualizer.speaker}/fitted/trn-011/meshes",
    "${path.dataset_dir}/talk_video/celebtalk/data/${model.visualizer.speaker}/fitted/trn-012/meshes",
    "${path.dataset_dir}/talk_video/celebtalk/data/${model.visualizer.speaker}/fitted/trn-013/meshes",
    "${path.dataset_dir}/talk_video/celebtalk/data/${model.visualizer.speaker}/fitted/trn-014/meshes",
  ]
  idle: "${path.dataset_dir}/talk_video/celebtalk/data/${model.visualizer.speaker}/fitted/identity/identity.obj"
  data_fps: "${data.CELEBTALK.DATA_FPS.${model.visualizer.speaker}}"
  avoffset: 0

misc:
  # - ["input_modality", "sent028", "/media/chaiyujin/Yuki-SSD2/iPhoneXRecord/version2/m0/neutral/sent028/audio.wav"]  # VOCA3 (from 1)
  # - ["input_modality", "sent028-f0", "/media/chaiyujin/Yuki-SSD2/iPhoneXRecord/version2/f0/neutral/sent028/audio.wav"]  # VOCA3 (from 1)

  - ["input_modality", "vld-000", "${path.dataset_dir}/talk_video/celebtalk/data/m003_iphoneXm0/vld-000"]  # VOCA3 (from 1)
  - ["input_modality", "vld-000-f0", "/media/chaiyujin/Yuki-SSD2/iPhoneXRecord/version2/f0/neutral/sent019/audio.wav"]  # VOCA3 (from 1)
  - ["input_modality", "vld-001", "${path.dataset_dir}/talk_video/celebtalk/data/m003_iphoneXm0/vld-001"]  # VOCA3 (from 1)
  - ["input_modality", "vld-001-f0", "/media/chaiyujin/Yuki-SSD2/iPhoneXRecord/version2/f0/neutral/sent020/audio.wav"]  # VOCA3 (from 1)
  - ["input_modality", "vld-002", "${path.dataset_dir}/talk_video/celebtalk/data/m003_iphoneXm0/vld-002"]  # VOCA3 (from 1)
  - ["input_modality", "vld-002-f0", "/media/chaiyujin/Yuki-SSD2/iPhoneXRecord/version2/f0/neutral/sent024/audio.wav"]  # VOCA3 (from 1)
  - ["input_modality", "vld-003", "${path.dataset_dir}/talk_video/celebtalk/data/m003_iphoneXm0/vld-003"]  # VOCA3 (from 1)
  - ["input_modality", "vld-003-f0", "/media/chaiyujin/Yuki-SSD2/iPhoneXRecord/version2/f0/neutral/sent025/audio.wav"]  # VOCA3 (from 1)
  - ["input_modality", "vld-004", "${path.dataset_dir}/talk_video/celebtalk/data/m003_iphoneXm0/vld-004"]  # VOCA3 (from 1)
  - ["input_modality", "vld-004-f0", "/media/chaiyujin/Yuki-SSD2/iPhoneXRecord/version2/f0/neutral/sent027/audio.wav"]  # VOCA3 (from 1)
  - ["input_modality", "vld-005", "${path.dataset_dir}/talk_video/celebtalk/data/m003_iphoneXm0/vld-005"]  # VOCA3 (from 1)
  - ["input_modality", "vld-005-f0", "/media/chaiyujin/Yuki-SSD2/iPhoneXRecord/version2/f0/neutral/sent029/audio.wav"]  # VOCA3 (from 1)
  - ["input_modality", "vld-006", "${path.dataset_dir}/talk_video/celebtalk/data/m003_iphoneXm0/vld-006"]  # VOCA3 (from 1)
  - ["input_modality", "vld-006-f0", "/media/chaiyujin/Yuki-SSD2/iPhoneXRecord/version2/f0/neutral/sent031/audio.wav"]  # VOCA3 (from 1)
  - ["input_modality", "vld-007", "${path.dataset_dir}/talk_video/celebtalk/data/m003_iphoneXm0/vld-007"]  # VOCA3 (from 1)
  - ["input_modality", "vld-007-f0", "/media/chaiyujin/Yuki-SSD2/iPhoneXRecord/version2/f0/neutral/sent035/audio.wav"]  # VOCA3 (from 1)


  - [
      "input_modality", "vld-001@tst-001",
      "${path.dataset_dir}/talk_video/celebtalk/data/m003_iphoneXm0/vld-001",
      {
        data_fps: 30, avoffset: 0,
        swap: "${path.dataset_dir}/talk_video/celebtalk/data/m003_iphoneXm0/fitted/tst-001/meshes",
        idle: "${path.dataset_dir}/talk_video/celebtalk/data/m003_iphoneXm0/fitted/identity/identity.obj"
      }
    ]
  - [
      "input_modality", "vld-001@03277_TA",
      "${path.dataset_dir}/talk_video/celebtalk/data/m003_iphoneXm0/vld-001",
      {
        data_fps: 60, avoffset: 6,
        swap: "${path.dataset_dir}/flame_mesh/vocaset_data/FaceTalk_170908_03277_TA/sentence03/offsets.npy",
      }
  ]

  # # Different input audio + same style code -> no impact on motion style.
  # - ["input_modality", "tst-001", "${path.dataset_dir}/talk_video/celebtalk/data/m003_iphoneXm0/tst-001"]  # VOCA3 (from 1)
  # - ["input_modality", "tst-001-f0", "/media/chaiyujin/Yuki-SSD2/iPhoneXRecord/version2/f0/neutral/sent153/audio.wav"]  # VOCA3 (from 1)
  # - ["input_modality", "tst-001-03277_TA", "${path.dataset_dir}/flame_mesh/vocaset_data/FaceTalk_170908_03277_TA/sentence03/audio.wav"]  # VOCA3 (from 1)

  # # Same audio, same subject different content -> little influence on motion style.
  # - [
  #     "input_modality", "tst-001@vld-000",
  #     "${path.dataset_dir}/talk_video/celebtalk/data/m003_iphoneXm0/tst-001",
  #     {
  #       data_fps: 30, avoffset: 0,
  #       swap: "${path.dataset_dir}/talk_video/celebtalk/data/m003_iphoneXm0/fitted/vld-000/meshes",
  #       idle: "${path.dataset_dir}/talk_video/celebtalk/data/m003_iphoneXm0/fitted/identity/identity.obj"
  #     }
  #   ]
  # - [
  #     "input_modality", "tst-001@vld-001",
  #     "${path.dataset_dir}/talk_video/celebtalk/data/m003_iphoneXm0/tst-001",
  #     {
  #       data_fps: 30, avoffset: 0,
  #       swap: "${path.dataset_dir}/talk_video/celebtalk/data/m003_iphoneXm0/fitted/vld-001/meshes",
  #       idle: "${path.dataset_dir}/talk_video/celebtalk/data/m003_iphoneXm0/fitted/identity/identity.obj"
  #     }
  #   ]
  # - [
  #     "input_modality", "tst-001@tst-001",
  #     "${path.dataset_dir}/talk_video/celebtalk/data/m003_iphoneXm0/tst-001",
  #     {
  #       data_fps: 30, avoffset: 0,
  #       swap: "${path.dataset_dir}/talk_video/celebtalk/data/m003_iphoneXm0/fitted/tst-001/meshes",
  #       idle: "${path.dataset_dir}/talk_video/celebtalk/data/m003_iphoneXm0/fitted/identity/identity.obj"
  #     }
  #   ]
  # - [
  #     "input_modality", "tst-001@tst-000",
  #     "${path.dataset_dir}/talk_video/celebtalk/data/m003_iphoneXm0/tst-001",
  #     {
  #       data_fps: 30, avoffset: 0,
  #       swap: "${path.dataset_dir}/talk_video/celebtalk/data/m003_iphoneXm0/fitted/tst-000/meshes",
  #       idle: "${path.dataset_dir}/talk_video/celebtalk/data/m003_iphoneXm0/fitted/identity/identity.obj"
  #     }
  #   ]

  # # Same audio, different subject same content -> great influence on motion style.
  # - [
  #     "input_modality", "tst-001@00024_TA",
  #     "${path.dataset_dir}/talk_video/celebtalk/data/m003_iphoneXm0/tst-001",
  #     {
  #       data_fps: 60, avoffset: 6,
  #       swap: "${path.dataset_dir}/flame_mesh/vocaset_data/FaceTalk_170731_00024_TA/sentence03/offsets.npy",
  #     }
  # ]
  # - [
  #     "input_modality", "tst-001@00138_TA",
  #     "${path.dataset_dir}/talk_video/celebtalk/data/m003_iphoneXm0/tst-001",
  #     {
  #       data_fps: 60, avoffset: 6,
  #       swap: "${path.dataset_dir}/flame_mesh/vocaset_data/FaceTalk_170809_00138_TA/sentence03/offsets.npy",
  #     }
  # ]
  # - [
  #     "input_modality", "tst-001@03274_TA",
  #     "${path.dataset_dir}/talk_video/celebtalk/data/m003_iphoneXm0/tst-001",
  #     {
  #       data_fps: 60, avoffset: 6,
  #       swap: "${path.dataset_dir}/flame_mesh/vocaset_data/FaceTalk_170811_03274_TA/sentence03/offsets.npy",
  #     }
  # ]
  # - [
  #     "input_modality", "tst-001@03277_TA",
  #     "${path.dataset_dir}/talk_video/celebtalk/data/m003_iphoneXm0/tst-001",
  #     {
  #       data_fps: 60, avoffset: 6,
  #       swap: "${path.dataset_dir}/flame_mesh/vocaset_data/FaceTalk_170908_03277_TA/sentence03/offsets.npy",
  #     }
  # ]

  # # Same audio, same subject different emotion
  # - [
  #     "input_modality", "tst-001@tst-003",
  #     "${path.dataset_dir}/talk_video/celebtalk/data/m003_iphoneXm0/tst-001",
  #     {
  #       data_fps: 30, avoffset: 0,
  #       swap: "${path.dataset_dir}/talk_video/celebtalk/data/m003_iphoneXm0/fitted/tst-003/meshes",
  #       idle: "${path.dataset_dir}/talk_video/celebtalk/data/m003_iphoneXm0/fitted/identity/identity.obj"
  #     }
  #   ]
  # - [
  #     "input_modality", "tst-001@tst-005",
  #     "${path.dataset_dir}/talk_video/celebtalk/data/m003_iphoneXm0/tst-001",
  #     {
  #       data_fps: 30, avoffset: 0,
  #       swap: "${path.dataset_dir}/talk_video/celebtalk/data/m003_iphoneXm0/fitted/tst-005/meshes",
  #       idle: "${path.dataset_dir}/talk_video/celebtalk/data/m003_iphoneXm0/fitted/identity/identity.obj"
  #     }
  #   ]
