do: ['misc']

default_extra:
  fps: 30
  avoffset: 0
  swap: "${path.dataset_dir}/talk_video/celebtalk/data/${model.visualizer.speaker}/fitted/trn-000/meshes"
  idle: "${path.dataset_dir}/talk_video/celebtalk/data/${model.visualizer.speaker}/fitted/identity/identity.obj"

misc:
  - ["vocaset/FaceTalk_170811_03274_TA", "sentence03@${model.visualizer.speaker}", "${path.dataset_dir}/flame_mesh/vocaset_data/FaceTalk_170811_03274_TA/sentence03"]
  - ["vocaset/FaceTalk_170915_00223_TA", "sentence01@${model.visualizer.speaker}", "${path.dataset_dir}/flame_mesh/vocaset_data/FaceTalk_170915_00223_TA/sentence01"]

  - ["test-clips", "speech-clip08", "${path.data_dir}/youtube/test-clips/speech-clip08.mp4"]
  - ["test-clips", "foreign@french_clip0", "${path.data_dir}/youtube/test-clips/foreign@french_clip0.mp4"]
