do: ['misc']

default_extra:
  fps: 30
  avoffset: 3
  swap: "${path.dataset_dir}/talk_video/facetalk/data/${model.visualizer.speaker}/fitted/sentence01/meshes"
  idle: "${path.dataset_dir}/talk_video/facetalk/data/${model.visualizer.speaker}/fitted/identity/identity.obj"

misc:
  - ["${model.visualizer.speaker}", "sentence35", "${path.dataset_dir}/talk_video/facetalk/data/${model.visualizer.speaker}/sentence35"]
  - ["${model.visualizer.speaker}", "sentence40", "${path.dataset_dir}/talk_video/facetalk/data/${model.visualizer.speaker}/sentence40"]

  # Special cases, where cmb3d may fail
  - ["vocaset/FaceTalk_170811_03274_TA", "sentence03", "${path.dataset_dir}/flame_mesh/vocaset_data/FaceTalk_170811_03274_TA/sentence03"]
