do: ['misc']

default_extra:
  swap: [
    "${path.dataset_dir}/talk_video/celebtalk/data/${model.visualizer.speaker}/fitted/trn-000/meshes",
    "${path.dataset_dir}/talk_video/celebtalk/data/${model.visualizer.speaker}/fitted/trn-001/meshes",
    "${path.dataset_dir}/talk_video/celebtalk/data/${model.visualizer.speaker}/fitted/trn-002/meshes",
    "${path.dataset_dir}/talk_video/celebtalk/data/${model.visualizer.speaker}/fitted/trn-003/meshes",
    "${path.dataset_dir}/talk_video/celebtalk/data/${model.visualizer.speaker}/fitted/trn-004/meshes",
    "${path.dataset_dir}/talk_video/celebtalk/data/${model.visualizer.speaker}/fitted/trn-005/meshes",
    "${path.dataset_dir}/talk_video/celebtalk/data/${model.visualizer.speaker}/fitted/trn-006/meshes",
    "${path.dataset_dir}/talk_video/celebtalk/data/${model.visualizer.speaker}/fitted/trn-007/meshes",
    "${path.dataset_dir}/talk_video/celebtalk/data/${model.visualizer.speaker}/fitted/trn-008/meshes",
    "${path.dataset_dir}/talk_video/celebtalk/data/${model.visualizer.speaker}/fitted/trn-009/meshes",
    "${path.dataset_dir}/talk_video/celebtalk/data/${model.visualizer.speaker}/fitted/trn-010/meshes",
    "${path.dataset_dir}/talk_video/celebtalk/data/${model.visualizer.speaker}/fitted/trn-011/meshes",
    "${path.dataset_dir}/talk_video/celebtalk/data/${model.visualizer.speaker}/fitted/trn-012/meshes",
  ]
  idle: "${path.dataset_dir}/talk_video/celebtalk/data/${model.visualizer.speaker}/fitted/identity/identity.obj"
  data_fps: "${data.CELEBTALK.DATA_FPS.${model.visualizer.speaker}}"
  avoffset: 0

misc:
  - ["${model.visualizer.speaker}", "vld-000", "${path.dataset_dir}/talk_video/celebtalk/data/${model.visualizer.speaker}/vld-000"]
  - ["${model.visualizer.speaker}", "vld-001", "${path.dataset_dir}/talk_video/celebtalk/data/${model.visualizer.speaker}/vld-001"]
  - ["${model.visualizer.speaker}", "vld-002", "${path.dataset_dir}/talk_video/celebtalk/data/${model.visualizer.speaker}/vld-002"]
  - ["${model.visualizer.speaker}", "vld-003", "${path.dataset_dir}/talk_video/celebtalk/data/${model.visualizer.speaker}/vld-003"]
  - ["${model.visualizer.speaker}", "vld-004", "${path.dataset_dir}/talk_video/celebtalk/data/${model.visualizer.speaker}/vld-004"]
  - ["${model.visualizer.speaker}", "vld-005", "${path.dataset_dir}/talk_video/celebtalk/data/${model.visualizer.speaker}/vld-005"]
  - ["${model.visualizer.speaker}", "vld-006", "${path.dataset_dir}/talk_video/celebtalk/data/${model.visualizer.speaker}/vld-006"]
  - ["${model.visualizer.speaker}", "vld-007", "${path.dataset_dir}/talk_video/celebtalk/data/${model.visualizer.speaker}/vld-007"]
  # Special cases, where cmb3d may fail
  - ["vocaset/FaceTalk_170811_03274_TA", "sentence03", "${path.dataset_dir}/flame_mesh/vocaset_data/FaceTalk_170811_03274_TA/sentence03"]
