do: ['misc']

default_extra:
  fps: 30
  avoffset: 0
  swap: "${path.dataset_dir}/talk_video/celebtalk/data/${model.visualizer.speaker}/fitted/trn-000/meshes"
  idle: "${path.dataset_dir}/talk_video/celebtalk/data/${model.visualizer.speaker}/fitted/identity/identity.obj"

misc:
  - ["user-study", "foreign@brasil",  "${path.data_dir}/youtube/user-study/foreign@brasil.mp4"]
  - ["user-study", "foreign@deutsch", "${path.data_dir}/youtube/user-study/foreign@deutsch.mp4"]
  - ["user-study", "foreign@french",  "${path.data_dir}/youtube/user-study/foreign@french.mp4"]
  - ["user-study", "foreign@italian", "${path.data_dir}/youtube/user-study/foreign@italian.mp4"]
  - ["user-study", "foreign@chinese", "${path.data_dir}/youtube/user-study/foreign@chinese.mp4"]

  - ["user-study", "noisy@f1_clip0",  "${path.data_dir}/youtube/user-study/noisy@f1_clip0.mp4"]
  - ["user-study", "noisy@f1_clip1",  "${path.data_dir}/youtube/user-study/noisy@f1_clip1.mp4"]
  - ["user-study", "noisy@nba_clip0", "${path.data_dir}/youtube/user-study/noisy@nba_clip0.mp4"]
  - ["user-study", "noisy@nba_clip1", "${path.data_dir}/youtube/user-study/noisy@nba_clip1.mp4"]
  - ["user-study", "noisy@nba_clip2", "${path.data_dir}/youtube/user-study/noisy@nba_clip2.mp4"]

  - ["user-study", "speech@clip0", "${path.data_dir}/youtube/user-study/speech@clip0.mp4"]
  - ["user-study", "speech@clip1", "${path.data_dir}/youtube/user-study/speech@clip1.mp4"]
  - ["user-study", "speech@clip2", "${path.data_dir}/youtube/user-study/speech@clip2.mp4"]
  - ["user-study", "speech@clip3", "${path.data_dir}/youtube/user-study/speech@clip3.mp4"]
  - ["user-study", "speech@clip4", "${path.data_dir}/youtube/user-study/speech@clip4.mp4"]
