do: ['vocaset']

default_extra:
  fps: 30
  avoffset: 1
  swap: "${path.dataset_dir}/talk_video/celebtalk/data/${model.visualizer.speaker}/fitted/trn-000/meshes"
  idle: "${path.dataset_dir}/talk_video/celebtalk/data/${model.visualizer.speaker}/fitted/identity/identity.obj"

# * for specific dataset
vocaset:
  data_dir: "${path.dataset_dir}/flame_mesh/vocaset_data"
  speakers: [
    [FaceTalk_170725_00137_TA, [0, 40]],
    [FaceTalk_170728_03272_TA, [0, 40]],
    [FaceTalk_170731_00024_TA, [0, 40]],
    [FaceTalk_170809_00138_TA, [0, 40]],
    [FaceTalk_170811_03274_TA, [0, 40]],
    [FaceTalk_170904_00128_TA, [0, 40]],
    [FaceTalk_170912_03278_TA, [0, 40]],
    [FaceTalk_170915_00223_TA, [0, 40]],
    # [FaceTalk_170811_03275_TA, [0, 5]], [FaceTalk_170811_03275_TA, [35, 40]],
    # [FaceTalk_170904_03276_TA, [0, 5]], [FaceTalk_170904_03276_TA, [35, 40]],
    # [FaceTalk_170908_03277_TA, [0, 5]], [FaceTalk_170908_03277_TA, [35, 40]],
    # [FaceTalk_170913_03279_TA, [0, 5]], [FaceTalk_170913_03279_TA, [35, 40]],
  ]
