_module_: src.datasets.flame_mesh

# data settings
audio: ${data.audio}
video: ${data.video}

# dataset setting
data_src: "???"
root: ${path.data_dir}/datasets/flame_mesh
speakers: []
used_seq_ids: null
seq_ids_used_duration: { all: full }
possible_clip_sources: ${.speakers}
style_ids: ${rev_map:${.speakers}}

# from network
src_seq_frames: ${model.data_info.src_seq_frames}
tgt_seq_frames: ${model.data_info.tgt_seq_frames}
src_seq_pads: ${model.data_info.src_seq_pads}
company_audio: "win"
using_audio_features: ["deepspeech"]
wanna_fps: ${model.wanna_fps}

# flags
need_audio: true
need_verts: true
need_refer: false
need_label: false

# subsequence Segment
training_hop_factor : 4.0

# data Augmentation
random_shift_alpha: 0
random_shift_index: true
random_aug_audio:
  time_stretch: 2
  feat_scaling: 0.2

# for landmarks
fw75_embed_path: ${path.root_dir}/src/mm_fitting/libmorph/data/fw75/landmarks_fw75.txt
